In [18]:
import numpy as np

In [19]:
weight = 0.1

def neural_network(input, weight):
    
    prediction = input * weight
    
    return prediction

In [20]:
number_of_toes = [8.5, 9.5, 10, 9]

input = number_of_toes[0]

pred = neural_network(input, weight)
print(pred)

0.8500000000000001


In [21]:
def elementwise_multiplication(vec_a, vec_b):
    assert(len(vec_a)==len(vec_b))
    output = []
    for i in range(len(vec_a)):
        output += [(vec_a[i] * vec_b[i])]   
    return output

def elementwise_addition(vec_a, vec_b):
    assert(len(vec_a)==len(vec_b))
    output = []
    for i in range(len(vec_a)):
        output += [(vec_a[i] + vec_b[i])] 
    return output

def vector_sum(vec_a):
    output = 0
    for i in vec_a:
        output += i   
    return output

def vector_average(vec_a):
    output = vector_sum(vec_a)/len(vec_a) 
    return output

def dot_product(vec_a, vec_b):
    return vector_sum(elementwise_multiplication(vec_a,vec_b))

In [22]:
vec_a = [0, 1, 2, 3, 4]
vec_b = [5, 6, 7, 8, 9]

ele_mul_test = elementwise_multiplication(vec_a, vec_b)
print('Element Multiplication Test: '+ str(ele_mul_test))

ele_add_test = elementwise_addition(vec_a, vec_b)
print('Element Addition Test: '+ str(ele_add_test))

vec_sum_test = vector_sum(vec_a)
print('Vector Sum Test:', vec_sum_test)

vec_avg_test = vector_average(vec_a)
print('Vector Average Test:', vec_avg_test)

dot_product_test = dot_product(vec_a,vec_b)
print('Dot Product Test:', dot_product_test)

Element Multiplication Test: [0, 6, 14, 24, 36]
Element Addition Test: [5, 7, 9, 11, 13]
Vector Sum Test: 10
Vector Average Test: 2.0
Dot Product Test: 80


In [23]:
def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred

weights = [0.1,0.2,0]

toes = [8.5, 9.5, 9.9, 9.0]
winloss = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], winloss[0], nfans[0]]
pred = neural_network(input, weights)
print(round(pred, 2))

0.98


In [26]:
weights = np.array([0.1, 0.2, 0])

def neural_network(input, weights):
    pred = input.dot(weights)
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0],wlrec[0],nfans[0]])
pred = neural_network(input,weights)
print(round(pred,2))

0.98


In [27]:
import numpy as np

# toes % win # fans
ih_wgt = np.array([
            [0.1, 0.2, -0.1], # hid[0]
            [-0.1,0.1, 0.9], # hid[1]
            [0.1, 0.4, 0.1]]).T # hid[2]


# hid[0] hid[1] hid[2]
hp_wgt = np.array([
            [0.3, 1.1, -0.3], # hurt?
            [0.1, 0.2, 0.0], # win?
            [0.0, 1.3, 0.1] ]).T # sad?

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):

    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred


toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65,0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0],wlrec[0],nfans[0]])

pred = neural_network(input,weights)
print(pred)

[0.2135 0.145  0.5065]


In [28]:
import numpy as np

a = np.array([0,1,2,3])
b = np.array([4,5,6,7])
c = np.array([[0,1,2,3],
              [4,5,6,7]])

d = np.zeros((2,4))
e = np.random.rand(2,5)

print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.26839497 0.6922295  0.32483823 0.07935017 0.14661206]
 [0.27208535 0.02548234 0.86961878 0.53346498 0.91215152]]


In [30]:
print(a * 0.1)
print(c * 0.2)
print(a * b)
print(a * b * 0.2)
print(a * c)

[0.  0.1 0.2 0.3]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]
